Lab: 張量與線性代數
================

此 lab 中，我們將會透過 `torch` 此套件，學習以下的主題。

1. 認識 `torch` 的張量（tensor）之基礎。

2. 了解如何對 `torch` 張量進行操弄。

3. 使用 `torch` 進行線性代數之運算。

4. 應用前述之知識，建立一可進行線性迴歸分析之類型（class）。

`torch`之安裝與基礎教學，可參考 [PyTorch官方網頁](https://pytorch.org/get-started/locally)。在安裝完成後，可透過以下的指令載入

In [31]:
import torch

## 張量之基礎

### 張量之輸入
`torch` 最基本的物件是張量（tensor），其與 `numpy` 的陣列（array）相當的類似。產生一個張量最基本的方法為，將所欲形成張量的資料（其可為 `python` 的 `list` 或是 `numpy` 的 `ndarray`），置於`torch.tensor`函數中


In [32]:
a = torch.tensor(data = [[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])
type(a)

torch.Tensor

透過 `type()`，可看見其屬於 `torch.Tensor` 此一類型（class），若欲了解 `a` 的樣貌，我們可使用 `print` 指令來列印其主要的內容

In [33]:
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


透過對 `a` 列印的結果，我們可觀察到：

+ `a` 內部的資料數值（value）為 `[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]`。

除此之外，`a` 還有兩個重要的屬性並未顯示在列印的結果中：

+ `a` 的尺寸（size）為 `(3, 4)`，表示 `a` 為一 $3 \times 4$ 之張量。在進行運算時，張量間的形狀需滿足某些條件，如相同，或是滿足某種廣播（broadcasting）的規則。
+ `a` 的資料類型（data type）為 `int64`，表示64位元的整數。在進行運算時，張量間的類型須相同。

稍後，我們會討論如何獲得 `torch` 張量的尺寸與資料類型。


### 張量之數值
若要獲得張量的資料數值（value），可透過 `.numpy()`獲得，其回傳該張量對應之 `numpy` 陣列

In [34]:
print("data of tensor is: \n", a.numpy())

data of tensor is: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


 `numpy` 陣列是 `python` 進行科學運算時，幾乎都會仰賴的資料格式。`torch` 內建了多種函數，以協助產生具有特別數值結構之張量：

In [35]:
print("tensor with all elements being ones \n",
      torch.ones(size = (4, 1)).numpy())
print("tensor with all elements being zeros \n",
      torch.zeros(size = (2, 3)).numpy())
print("identity-like tensor \n",
      torch.eye(n = 3, m = 5).numpy())
print("diagonal matrix \n",
      torch.diag(input = torch.tensor([1, 2, 3, 4])).numpy())

tensor with all elements being ones 
 [[1.]
 [1.]
 [1.]
 [1.]]
tensor with all elements being zeros 
 [[0. 0. 0.]
 [0. 0. 0.]]
identity-like tensor 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
diagonal matrix 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


`torch` 亦可指定分配產生隨機的資料

In [36]:
print("tensor with random elements from uniform(0, 1) \n",
      torch.rand(size = (2, 6)).numpy())
print("tensor with uninitialized data \n",
      torch.empty(size = (2, 6)).numpy())

tensor with random elements from uniform(0, 1) 
 [[0.75320894 0.670635   0.43403876 0.3943047  0.2493949  0.08474314]
 [0.78782105 0.9415814  0.0187099  0.6755545  0.61599994 0.6288617 ]]
tensor with uninitialized data 
 [[9.8090893e-45 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 [2.6660814e-09 6.6473279e+22 3.4180928e-06 2.1769561e+23 2.6706910e+23
  1.7679558e-04]]


### 張量之形狀

張量之形狀與形狀維度之數量，可透過張量物件的 `.size()`（或 `.shape`） 與 `dim` 方法來獲得

In [37]:
print("size of tensor is", a.size())
print("size of tensor is", a.shape)
print("dim of tensor is", a.dim())

size of tensor is torch.Size([3, 4])
size of tensor is torch.Size([3, 4])
dim of tensor is 2


如果要對張量的形狀進行改變的話，可透過 `.view()` 此方法獲得

In [38]:
print("tensor with shape (4, 3): \n",
      a.view(size = (4, 3)).numpy())
print("tensor with shape (2, 2, 3): \n",
      a.view(size = (2, 2, 3)).numpy())
print("tensor with shape (12, 1): \n",
      a.view(size = (12, 1)).numpy())
print("tensor with shape (12, 1) by (-1, 1): \n",
      a.view(size = (-1, 1)).numpy())
print("tensor with shape (12,): \n",
      a.view(size = (12, )).numpy())


tensor with shape (4, 3): 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
tensor with shape (2, 2, 3): 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
tensor with shape (12, 1): 
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
tensor with shape (12, 1) by (-1, 1): 
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
tensor with shape (12,): 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


注意，`(12, 1)` 與 `(12,)` 兩種形狀是不一樣的，前者為2d的張量，後者為1d的張量。在進行張量操弄時，若將兩者混淆，很可能會帶來錯誤的計算結果。另外，-1表示該面向對應之尺寸，由其它面向決定。


### 張量之資料類型
張量的資料類型，可透過 `.dtype` 方法獲得

In [39]:
print("data type of tensor is", a.dtype)

data type of tensor is torch.int64


若是要調整資料類型的話，則可透過 `.type()` 此方法：

In [40]:
print(a.type(torch.float64))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)


`torch` 內建多種資料類型，包含整數類型（如 `torch.int32` 與 `torch.int64`）與浮點數類型（如 `torch.float32` 與 `torch.float64`），完整的資料類型請見 [torch.Tensor文件](https://pytorch.org/docs/stable/tensors.html)。

在進行張量的數學運算時，請務必確認張量間的資料類型都是一致的，而 `torch` 常用之資料類型為 `torch.float32` 與 `torch.float64`，前者所需的記憶體較小，但運算結果的數值誤差較大。


## 張量之操弄

### 張量之切片

若要擷取一張量特定的行（row）或列（column）的話，則可透過切片（slicing）的功能獲得。`torch` 張量的切片方式，與 `numpy` 類似，皆使用中括號 `[]`，再搭配所欲擷取資料行列的索引（index）獲得。

In [41]:
print("extract 1st row: \n",
      a[0, :].numpy())
print("extract 1st and 2nd rows: \n",
      a[:2, :].numpy())
print("extract 2nd column: \n",
      a[:, 1].numpy())
print("extract 2nd and 3rd columns: \n",
      a[:, 1:3].numpy())

extract 1st row: 
 [1 2 3 4]
extract 1st and 2nd rows: 
 [[1 2 3 4]
 [5 6 7 8]]
extract 2nd column: 
 [ 2  6 10]
extract 2nd and 3rd columns: 
 [[ 2  3]
 [ 6  7]
 [10 11]]


進行切片時，有幾項重點需要注意。

+ 各面向之索引從0開始。
+ 負號表示從結尾數回來，如 `-1` 表示最後一個位置。
+ `:`表示該面向所有元素皆挑選。
+ `start:stop` 表示從 `start` 開始挑選到 `stop-1`。
+ `start:stop:step` 表示從 `start` 開始到 `stop-1`，間隔 `step` 挑選。

### 張量之串接
多個張量在維度可對應之前提下，可透過 `torch.cat` 串接

In [42]:
print("vertical concatenation \n",
      torch.cat([a, a], dim = 0).numpy())
print("horizontal concatenation \n",
      torch.cat([a, a], dim = 1).numpy())

vertical concatenation 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
horizontal concatenation 
 [[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]


## 張量之運算
考慮以下 `a` 與 `b` 兩張量

In [43]:
a = torch.tensor(data = [[1, 2], [3, 4], [5, 6]],
                dtype = torch.float64)
b = torch.tensor(data = [[1, 2], [1, 2], [1, 2]],
                dtype = torch.float64)
print("tensor a is \n", a.numpy())
print("tensor b is \n", b.numpy())


tensor a is 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
tensor b is 
 [[1. 2.]
 [1. 2.]
 [1. 2.]]


我們將使用 `a` 與 `b` 來展示如何使用 `torch` 進行張量間的計算。

### 張量元素對元素之運算
透過 `torch` 的數學函數，可進行張量元素對元素的四則運算

In [44]:
print("element-wise add \n",
      torch.add(a, b))
print("element-wise subtract \n",
      torch.sub(a, b))
print("element-wise multiply \n",
      torch.mul(a, b))
print("element-wise divide \n",
      torch.div(a, b))

element-wise add 
 tensor([[2., 4.],
        [4., 6.],
        [6., 8.]], dtype=torch.float64)
element-wise subtract 
 tensor([[0., 0.],
        [2., 2.],
        [4., 4.]], dtype=torch.float64)
element-wise multiply 
 tensor([[ 1.,  4.],
        [ 3.,  8.],
        [ 5., 12.]], dtype=torch.float64)
element-wise divide 
 tensor([[1., 1.],
        [3., 2.],
        [5., 3.]], dtype=torch.float64)


前述採用的函數，皆可取代為其所對應之運算子計算

In [45]:
print("element-wise add \n", a + b)
print("element-wise subtract \n", a - b)
print("element-wise multiply \n", a * b)
print("element-wise divide \n", a / b)

element-wise add 
 tensor([[2., 4.],
        [4., 6.],
        [6., 8.]], dtype=torch.float64)
element-wise subtract 
 tensor([[0., 0.],
        [2., 2.],
        [4., 4.]], dtype=torch.float64)
element-wise multiply 
 tensor([[ 1.,  4.],
        [ 3.,  8.],
        [ 5., 12.]], dtype=torch.float64)
element-wise divide 
 tensor([[1., 1.],
        [3., 2.],
        [5., 3.]], dtype=torch.float64)


若需要進行絕對值、對數、指數等較為進階之數學運算，可以至 [troch官方文件](https://pytorch.org/docs/stable/torch.html#math-operations) 此模組中尋找對應的數學函數。

### 張量線性代數之運算
除了簡單的四則運算外，當張量的 `dim` 為2時，`torch` 提供了進行線性代數（linear algebra）相關的函數，如

+ 矩陣轉置（matrix transpose）

In [46]:
a_t = torch.transpose(input=a, dim0=0, dim1=1)
print("transpose of a is \n",
      a_t.numpy())

transpose of a is 
 [[1. 3. 5.]
 [2. 4. 6.]]


+ 矩陣乘法（matrix multiplication）

In [47]:
c = a_t @ a
print("c = a_t @ a is \n",
      c.numpy())

c = a_t @ a is 
 [[35. 44.]
 [44. 56.]]


+ 反矩陣（matrix inverse）

In [48]:
c_inv = torch.inverse(input = c)
print("inverse of c is \n",
      c_inv.numpy()) # c @ c_inv should be identity matrix
print("check for inverse (left) \n",
      (c_inv @ c).numpy())
print("check for inverse (right) \n",
      (c @ c_inv).numpy())

inverse of c is 
 [[ 2.33333333 -1.83333333]
 [-1.83333333  1.45833333]]
check for inverse (left) 
 [[ 1.00000000e+00 -1.42108547e-14]
 [ 0.00000000e+00  1.00000000e+00]]
check for inverse (right) 
 [[1. 0.]
 [0. 1.]]


+ Cholesky 拆解（Cholesky decomposition）

In [49]:
c_chol = torch.cholesky(input = c)
print("Cholesky factor of c is \n",
      c_chol.numpy())
print("check for Cholesky decomposition \n",
      (c_chol @ torch.transpose(c_chol, 0 , 1)).numpy())

Cholesky factor of c is 
 [[5.91607978 0.        ]
 [7.43735744 0.82807867]]
check for Cholesky decomposition 
 [[35. 44.]
 [44. 56.]]


+ 特徵拆解（eigen-decomposition）

In [50]:
e, v = torch.symeig(input = c, eigenvectors=True)
print("eigenvalue of c is \n",
      e.numpy())
print("eigenvector of c is \n",
      v.numpy())
print("check for eigen-decomposition \n",
      (v @ torch.diag(e) @
       torch.transpose(v, 0 , 1)).numpy())


eigenvalue of c is 
 [ 0.26450509 90.73549491]
eigenvector of c is 
 [[-0.78489445  0.61962948]
 [ 0.61962948  0.78489445]]
check for eigen-decomposition 
 [[35. 44.]
 [44. 56.]]


+ 奇異值拆解（singular value decomposition）

In [51]:
u, s, v = torch.svd(input = a)
print("singular value of a is \n",
      s.numpy())
print("left singular vector of a is \n",
      u.numpy())
print("right singular vector of a is \n",
      v.numpy())
print("check for singular value decomposition \n",
      (u @ torch.diag(s) @
       torch.transpose(v, 0, 1)).numpy())


singular value of a is 
 [9.52551809 0.51430058]
left singular vector of a is 
 [[-0.2298477   0.88346102]
 [-0.52474482  0.24078249]
 [-0.81964194 -0.40189603]]
right singular vector of a is 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
check for singular value decomposition 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


### 對張量之數值進行摘要
`torch` 提供了一些化約（reduction）的函數，對張量內的數值進行摘要

In [52]:
print("calculate mean \n",
      torch.mean(input = a).numpy())
print("calculate standard deviation \n",
      torch.std(input = a).numpy())
print("calculate max \n",
      torch.max(input = a).numpy())
print("calculate min \n",
      torch.min(input = a).numpy())

calculate mean 
 3.5
calculate standard deviation 
 1.8708286933869707
calculate max 
 6.0
calculate min 
 1.0


我們亦可對張量的各面向，進行前述的摘要。以平均數為例：

In [53]:
print("calculate mean for each column \n",
      torch.mean(input = a, dim=0).numpy())
print("calculate mean for each row \n",
      torch.mean(input = a, dim=1).numpy())

calculate mean for each column 
 [3. 4.]
calculate mean for each row 
 [1.5 3.5 5.5]


其它的化約函數，可以參考[官方文件](https://pytorch.org/docs/stable/torch.html#reduction-ops)。

## 實徵範例

### 產生線性迴歸資料

在開始之前，我們先設定一種子，以讓後續的亂數生成都能夠獲得相同的結果（不過，這裡的 `manual_seed` 僅適用於CPU，若使用GPU，請改為 `torch.cuda.manual_seed`）。

In [54]:
torch.manual_seed(48)


In [55]:
# define a function to generate x and y
def generate_data(n_sample, weight,
                  bias = 0,
                  std_residual = 1,
                  mean_feature = 0,
                  std_feature = 1,
                  dtype = torch.float64):
    weight = torch.tensor(weight, dtype = dtype)
    n_feature = weight.shape[0]
    x = torch.normal(mean = mean_feature,
                     std = std_feature,
                     size = (n_sample, n_feature),
                     dtype = dtype)
    e = torch.normal(mean = 0,
                     std = std_residual,
                     size = (n_sample, 1),
                     dtype = dtype)
    weight = weight.view(size = (-1, 1))
    y = bias + x @ weight + e
    return x, y

In [56]:
# run generate_data
x, y = generate_data(n_sample = 10,
                     weight = [-5, 3, 0],
                     bias = 5,
                     std_residual = 1,
                     mean_feature = 10,
                     std_feature = 3,
                     dtype = torch.float64)
print("feature matrix x is \n", x.numpy())
print("response vector y is \n", y.numpy())



feature matrix x is 
 [[10.86425232  2.85930239 12.99748957]
 [ 7.98709525  9.79137811 12.98202577]
 [ 8.40585824 13.31645195  4.51125723]
 [10.52843635 10.28388618  8.43102705]
 [11.25624976 12.04005459 12.59301479]
 [12.31145327  9.15153143  7.96220487]
 [11.49807312 14.63609048  6.82995236]
 [11.7234386   7.16098399  9.8980089 ]
 [ 7.24735628  7.5570991   5.9154331 ]
 [11.05035931 10.47430089  4.86376669]]
response vector y is 
 [[-42.98404441]
 [ -4.94309144]
 [  0.31840093]
 [-16.21407503]
 [-13.77391657]
 [-31.18360077]
 [ -8.4871242 ]
 [-31.53590804]
 [ -7.8563037 ]
 [-19.27007283]]


### 計算模型參數

In [57]:
# define a function to calculate model parameter
def calculate_parameter(x, y, dtype = torch.float64):
    if x.dtype is not dtype:
        x = x.type(dtype = dtype)
    if y.dtype is not dtype:
        y = y.type(dtype = dtype)
    u = torch.ones(size = (x.size()[0], 1), dtype = dtype)
    x_design = torch.cat([u, x], dim = 1)
    parameter = torch.inverse(
        torch.transpose(x_design, dim0=0, dim1=1) @ x_design) @ \
                torch.transpose(x_design, dim0=0, dim1=1) @ y
    bias = parameter[0, 0]
    weight = parameter[1:, 0]
    return bias, weight

In [58]:
# run calculate_parameter
x, y = generate_data(n_sample = 1000,
                     weight = [-5, 3, 0],
                     bias = 5,
                     std_residual = 1,
                     mean_feature = 10,
                     std_feature = 3,
                     dtype = torch.float64)
bias, weight = calculate_parameter(x, y)
print("bias estimate is \n", bias.numpy())
print("weight estimate is \n", weight.numpy())


bias estimate is 
 4.996612423766793
weight estimate is 
 [-4.98003037  2.98762589 -0.00737968]


### 建立一進行迴歸分析之物件

In [59]:
# define a class to fit linear regression
class LinearRegression():
    def __init__(self, dtype = torch.float64):
        self.dtype = dtype
        self.bias = None
        self.weight = None
    def fit(self, x, y):
        if x.dtype is not self.dtype:
            x = x.type(dtype = self.dtype)
        if y.dtype is not self.dtype:
            y = y.type(dtype = self.dtype)
        u = torch.ones(size = (x.size()[0], 1), dtype = self.dtype)
        x_design = torch.cat([u, x], dim = 1)
        parameter = torch.inverse(
            torch.transpose(x_design, dim0=0, dim1=1) @ x_design) @ \
                    torch.transpose(x_design, dim0=0, dim1=1) @ y
        self.bias = parameter[0, 0]
        self.weight = parameter[1:, 0]
        return self

In [60]:
model_lr = LinearRegression()
model_lr.fit(x, y)
print("bias estimate is \n", model_lr.bias.numpy())
print("weight estimate is \n", model_lr.weight.numpy())



bias estimate is 
 4.996612423766793
weight estimate is 
 [-4.98003037  2.98762589 -0.00737968]
