Lab: 最大概似估計
================

In [1]:
import torch

In [2]:
from torch.distributions import Normal
normal = Normal(loc=0., scale=1.)

In [3]:
print("random sample with shape ():\n",
      normal.sample())
print("random sample with shape (3,):\n",
      normal.sample(sample_shape=(3,)))
print("random sample with shape (2,3):\n",
      normal.sample(sample_shape=(2, 3)))

random sample with shape ():
 tensor(-0.0269)
random sample with shape (3,):
 tensor([ 0.1813,  0.4746, -1.5740])
random sample with shape (2,3):
 tensor([[-1.1004,  2.3509, -1.6805],
        [ 0.4067,  1.5799,  0.7578]])


In [4]:
print("cumulative probability given value with shape ():\n",
      normal.cdf(value=0), "\n")
print("cumulative probability given value with (3,):\n",
      normal.cdf(value=torch.Tensor([-1, 0, .5])), "\n")
print("cumulative probability given value with (2,3):\n",
      normal.cdf(value=torch.Tensor([[-1, 0, .5], [-2, 1, 3]])))

cumulative probability given value with shape ():
 tensor(0.5000) 

cumulative probability given value with (3,):
 tensor([0.1587, 0.5000, 0.6915]) 

cumulative probability given value with (2,3):
 tensor([[0.1587, 0.5000, 0.6915],
        [0.0228, 0.8413, 0.9987]])


In [5]:
print("cumulative probability given value with shape ():\n",
      normal.log_prob(value=0), "\n")
print("cumulative probability given value with (3,):\n",
      normal.log_prob(value=torch.Tensor([-1, 0, .5])), "\n")
print("cumulative probability given value with (2,3):\n",
      normal.log_prob(value=torch.Tensor([[-1, 0, .5], [-2, 1, 3]])))

cumulative probability given value with shape ():
 tensor(-0.9189) 

cumulative probability given value with (3,):
 tensor([-1.4189, -0.9189, -1.0439]) 

cumulative probability given value with (2,3):
 tensor([[-1.4189, -0.9189, -1.0439],
        [-2.9189, -1.4189, -5.4189]])


In [6]:
print(normal)

Normal(loc: 0.0, scale: 1.0)


In [7]:
print(normal.batch_shape)
print(normal.event_shape)

torch.Size([])
torch.Size([])


In [8]:
normal_batch = Normal(loc=torch.Tensor([0., 1.]), scale=torch.Tensor([1., 1.5]))
print(normal_batch)

Normal(loc: torch.Size([2]), scale: torch.Size([2]))


In [9]:
print("random sample with sample_shape ():\n",
      normal_batch.sample(), "\n")
print("random sample with sample_shape (3,):\n",
      normal_batch.sample(sample_shape=(3,)), "\n")
print("random sample with sample_shape (2,3):\n",
      normal_batch.sample(sample_shape=(2,3)))


random sample with sample_shape ():
 tensor([0.6592, 0.2241]) 

random sample with sample_shape (3,):
 tensor([[-1.9329, -0.6830],
        [-0.3982,  0.8844],
        [ 0.2287,  0.8980]]) 

random sample with sample_shape (2,3):
 tensor([[[ 0.1438, -1.4765],
         [-0.6314, -2.3386],
         [ 0.0736, -0.8309]],

        [[ 0.4519,  2.8137],
         [ 1.0334,  2.3478],
         [-1.1222,  2.5093]]])


In [10]:
print("log-probability given value with shape ():\n",
      normal_batch.log_prob(0), "\n")
print("log-probability given value with shape (2,):\n",
      normal_batch.log_prob(torch.Tensor([0, 0])), "\n")
print("log-probability given value with shape (2,1):\n",
      normal_batch.log_prob(torch.Tensor([[0], [0]])))

log-probability given value with shape ():
 tensor([-0.9189, -1.5466]) 

log-probability given value with shape (2,):
 tensor([-0.9189, -1.5466]) 

log-probability given value with shape (2,1):
 tensor([[-0.9189, -1.5466],
        [-0.9189, -1.5466]])


In [11]:
from torch.distributions import MultivariateNormal
mvn = MultivariateNormal(
    loc=torch.Tensor([0, 1]),
    scale_tril=torch.cholesky(torch.Tensor([[1., 0.], [0., .5]])))
print(mvn)


MultivariateNormal(loc: torch.Size([2]), scale_tril: torch.Size([2, 2]))


In [12]:
print("random sample with sample_shape ():\n",
      mvn.sample(), "\n")
print("random sample with sample_shape (3,):\n",
      mvn.sample(sample_shape=(3,)), "\n")
print("random sample with sample_shape (2, 3):\n",
      mvn.sample(sample_shape=(2, 3)))

random sample with sample_shape ():
 tensor([1.0156, 0.9904]) 

random sample with sample_shape (3,):
 tensor([[0.6730, 1.7196],
        [1.4520, 1.6104],
        [0.9953, 0.8920]]) 

random sample with sample_shape (2, 3):
 tensor([[[ 0.4206,  2.3159],
         [ 1.3656,  0.3986],
         [-1.4932,  0.8257]],

        [[ 0.9491,  1.8949],
         [-0.0903,  1.3086],
         [ 0.9624,  1.7623]]])


In [13]:
print("log-probability given value with shape (2,):\n",
      mvn.log_prob(torch.Tensor([0, 0])), "\n")
print("log-probability given value with shape (2,1):\n",
      mvn.log_prob(torch.Tensor([[0, 0], [0, 0]])))

log-probability given value with shape (2,):
 tensor(-2.4913) 

log-probability given value with shape (2,1):
 tensor([-2.4913, -2.4913])


In [14]:
from torch.distributions import Independent
normal_batch = Independent(normal_batch, reinterpreted_batch_ndims=1)
print(normal_batch.batch_shape)
print(normal_batch.event_shape)


torch.Size([])
torch.Size([2])


In [15]:
mvn_batch = MultivariateNormal(
    loc=torch.Tensor([[0, 1],[1, 2],[2, 3]]),
    scale_tril=torch.cholesky(torch.Tensor([[1., .2], [.2, .5]])))
mvn_batch

MultivariateNormal(loc: torch.Size([3, 2]), scale_tril: torch.Size([3, 2, 2]))

In [16]:
print("random sample with sample_shape ():\n",
      mvn_batch.sample(), "\n")
print("random sample with sample_shape (3,):\n",
      mvn_batch.sample(sample_shape=(3,)), "\n")
print("random sample with sample_shape (2, 3):\n",
      mvn_batch.sample(sample_shape=(2, 3)))


random sample with sample_shape ():
 tensor([[-0.2331,  1.5183],
        [ 1.7790,  3.0896],
        [ 3.0205,  2.8895]]) 

random sample with sample_shape (3,):
 tensor([[[-0.0379,  1.1380],
         [ 0.5762,  1.5213],
         [ 0.7794,  2.0890]],

        [[ 0.8970,  1.6773],
         [ 1.8447,  1.9486],
         [ 2.2285,  3.4417]],

        [[ 0.3830,  1.1698],
         [ 1.3693,  2.5909],
         [ 4.3556,  3.5252]]]) 

random sample with sample_shape (2, 3):
 tensor([[[[-0.8003,  0.4242],
          [ 2.8311,  2.1075],
          [ 1.8430,  4.0265]],

         [[ 1.2002, -0.6745],
          [ 1.6156,  2.8534],
          [ 1.1031,  3.1149]],

         [[-2.1968,  0.6993],
          [ 0.8145,  1.9768],
          [ 0.7687,  1.9745]]],


        [[[-0.2976, -0.4327],
          [ 2.3306,  1.9456],
          [ 0.9440,  3.0004]],

         [[-0.2018,  0.5385],
          [ 0.8988,  2.7793],
          [ 1.3715,  1.6832]],

         [[ 0.1082,  1.4043],
          [ 1.6704,  2.2995],
     

In [17]:
mu_true = torch.tensor([5.])
sigma_true = torch.tensor([2.])
normal_model_true = Normal(
    loc=mu_true,
    scale=sigma_true)
print("normal model:\n", normal_model_true, "\n")

normal model:
 Normal(loc: tensor([5.]), scale: tensor([2.])) 



In [18]:
sample_size = 1000
x = normal_model_true.sample(sample_shape=(sample_size,))
loss_value = -torch.mean(torch.sum(normal_model_true.log_prob(x), dim = 1))
print("negative likelihood value is", loss_value)


negative likelihood value is tensor(2.1206)


In [19]:
epochs = 200
lr = 1.0
mu = torch.tensor([0.], requires_grad=True)
sigma = torch.tensor([1.], requires_grad=True)
optimizer = torch.optim.Adam([mu, sigma], lr=.5)
for epoch in range(epochs):
    normal_model = Normal(loc=mu, scale=sigma)
    loss_value = -torch.mean(normal_model.log_prob(x))
    optimizer.zero_grad()
    loss_value.backward() # compute the gradient
    optimizer.step()

In [20]:
print("ML mean by gradient descent:", mu)
print("ML std by gradient descent:", sigma)

ML mean by gradient descent: tensor([5.0709], requires_grad=True)
ML std by gradient descent: tensor([2.0162], requires_grad=True)


In [21]:
print("ML mean by formula:", torch.mean(x))
print("ML std by formula:", torch.std(x, unbiased=False))

ML mean by formula: tensor(5.0709)
ML std by formula: tensor(2.0156)


In [22]:
mu_true = torch.tensor([-1., 0., 1.])
sigma_tril_true = torch.tensor([[3., 0., 0.], [2., 1., 0.], [.4, .5, .5]])
mvn_model_true = MultivariateNormal(
    loc=mu_true,
    scale_tril=sigma_tril_true)
print("true mean vector: \n", mvn_model_true.mean)
print("true covariance matrix: \n", mvn_model_true.covariance_matrix)

true mean vector: 
 tensor([-1.,  0.,  1.])
true covariance matrix: 
 tensor([[9.0000, 6.0000, 1.2000],
        [6.0000, 5.0000, 1.3000],
        [1.2000, 1.3000, 0.6600]])


In [23]:
sample_size = 1000
x = mvn_model_true.sample(sample_shape=(sample_size,))
loss_value = -torch.mean(mvn_model_true.log_prob(x))
print("negative likelihood value is", loss_value)


negative likelihood value is tensor(4.6601)


In [24]:
epochs = 500
lr = .1
mu = torch.tensor(
    [0., 0., 0.], requires_grad=True)
sigma_tril = torch.tensor(
    [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]],
    requires_grad=True)
optimizer = torch.optim.Adam([mu, sigma_tril], lr=lr)

for epoch in range(epochs):
    mvn_model = MultivariateNormal(
    loc=mu,
    scale_tril=sigma_tril)
    loss_value = -torch.mean(mvn_model.log_prob(x))
    optimizer.zero_grad()
    loss_value.backward() # compute the gradient
    optimizer.step()

In [25]:
print("ML mean by gradient descent: \n",
      mu)
print("ML covariance by gradient descent: \n",
      sigma_tril @ torch.transpose(sigma_tril, 0, 1))

ML mean by gradient descent: 
 tensor([-0.9338,  0.0233,  1.0003], requires_grad=True)
ML covariance by gradient descent: 
 tensor([[9.4390, 6.2599, 1.2521],
        [6.2599, 5.0985, 1.3125],
        [1.2521, 1.3125, 0.6612]], grad_fn=<MmBackward>)


In [26]:
sample_mean = torch.mean(x, dim = 0)
sample_moment2 = (torch.transpose(x, 0, 1) @ x) / sample_size
sample_cov = sample_moment2 - torch.ger(sample_mean, sample_mean)
print("ML mean by formula: \n",
      sample_mean)
print("ML covariance by formula: \n",
      sample_cov)

ML mean by formula: 
 tensor([-0.9338,  0.0233,  1.0003])
ML covariance by formula: 
 tensor([[9.4390, 6.2599, 1.2521],
        [6.2599, 5.0985, 1.3125],
        [1.2521, 1.3125, 0.6612]])
