Lab: 最大概似估計
================

In [1]:
import torch

In [2]:
from torch.distributions import Normal
normal = Normal(loc=0., scale=1.)

In [3]:
print("random sample with shape ():\n",
      normal.sample())
print("random sample with shape (3,):\n",
      normal.sample(sample_shape=(3,)))
print("random sample with shape (2,3):\n",
      normal.sample(sample_shape=(2, 3)))

random sample with shape ():
 tensor(-0.5375)
random sample with shape (3,):
 tensor([ 0.6526,  0.7198, -0.1674])
random sample with shape (2,3):
 tensor([[ 0.4500,  1.3059, -1.9399],
        [-0.8112, -0.9248, -0.1910]])


In [4]:
print("cumulative probability given value with shape ():\n",
      normal.cdf(value=0), "\n")
print("cumulative probability given value with (3,):\n",
      normal.cdf(value=torch.Tensor([-1, 0, .5])), "\n")
print("cumulative probability given value with (2,3):\n",
      normal.cdf(value=torch.Tensor([[-1, 0, .5], [-2, 1, 3]])))

cumulative probability given value with shape ():
 tensor(0.5000) 

cumulative probability given value with (3,):
 tensor([0.1587, 0.5000, 0.6915]) 

cumulative probability given value with (2,3):
 tensor([[0.1587, 0.5000, 0.6915],
        [0.0228, 0.8413, 0.9987]])


In [5]:
print("cumulative probability given value with shape ():\n",
      normal.log_prob(value=0), "\n")
print("cumulative probability given value with (3,):\n",
      normal.log_prob(value=torch.Tensor([-1, 0, .5])), "\n")
print("cumulative probability given value with (2,3):\n",
      normal.log_prob(value=torch.Tensor([[-1, 0, .5], [-2, 1, 3]])))

cumulative probability given value with shape ():
 tensor(-0.9189) 

cumulative probability given value with (3,):
 tensor([-1.4189, -0.9189, -1.0439]) 

cumulative probability given value with (2,3):
 tensor([[-1.4189, -0.9189, -1.0439],
        [-2.9189, -1.4189, -5.4189]])


In [6]:
print(normal)

Normal(loc: 0.0, scale: 1.0)


In [7]:
print(normal.batch_shape)
print(normal.event_shape)

torch.Size([])
torch.Size([])


In [8]:
normal_batch = Normal(loc=torch.Tensor([0., 1.]), scale=torch.Tensor([1., 1.5]))
print(normal_batch)

Normal(loc: torch.Size([2]), scale: torch.Size([2]))


In [9]:
print("random sample with sample_shape ():\n",
      normal_batch.sample(), "\n")
print("random sample with sample_shape (3,):\n",
      normal_batch.sample(sample_shape=(3,)), "\n")
print("random sample with sample_shape (2,3):\n",
      normal_batch.sample(sample_shape=(2,3)))


random sample with sample_shape ():
 tensor([0.2959, 2.6718]) 

random sample with sample_shape (3,):
 tensor([[-1.6329, -0.4173],
        [ 0.6373, -1.9564],
        [-0.8026,  1.2737]]) 

random sample with sample_shape (2,3):
 tensor([[[ 0.7441, -1.5493],
         [-0.2312,  1.6810],
         [-0.3377, -0.9645]],

        [[-0.3351,  0.3939],
         [ 0.9689,  2.5815],
         [-0.8018,  0.1117]]])


In [10]:
print("log-probability given value with shape ():\n",
      normal_batch.log_prob(0), "\n")
print("log-probability given value with shape (2,):\n",
      normal_batch.log_prob(torch.Tensor([0, 0])), "\n")
print("log-probability given value with shape (2,1):\n",
      normal_batch.log_prob(torch.Tensor([[0], [0]])))

log-probability given value with shape ():
 tensor([-0.9189, -1.5466]) 

log-probability given value with shape (2,):
 tensor([-0.9189, -1.5466]) 

log-probability given value with shape (2,1):
 tensor([[-0.9189, -1.5466],
        [-0.9189, -1.5466]])


In [11]:
from torch.distributions import MultivariateNormal
mvn = MultivariateNormal(
    loc=torch.Tensor([0, 1]),
    scale_tril=torch.cholesky(torch.Tensor([[1., 0.], [0., .5]])))
print(mvn)


MultivariateNormal(loc: torch.Size([2]), scale_tril: torch.Size([2, 2]))


In [12]:
print("random sample with sample_shape ():\n",
      mvn.sample(), "\n")
print("random sample with sample_shape (3,):\n",
      mvn.sample(sample_shape=(3,)), "\n")
print("random sample with sample_shape (2, 3):\n",
      mvn.sample(sample_shape=(2, 3)))

random sample with sample_shape ():
 tensor([ 0.0095, -0.3466]) 

random sample with sample_shape (3,):
 tensor([[0.5276, 0.9779],
        [0.8853, 1.4603],
        [0.4926, 2.0687]]) 

random sample with sample_shape (2, 3):
 tensor([[[-1.3499,  1.6449],
         [ 0.1050, -0.4897],
         [ 0.0898,  0.6144]],

        [[-0.7772,  1.8796],
         [-0.9441,  1.8775],
         [-0.4178,  1.2061]]])


In [13]:
print("log-probability given value with shape (2,):\n",
      mvn.log_prob(torch.Tensor([0, 0])), "\n")
print("log-probability given value with shape (2,1):\n",
      mvn.log_prob(torch.Tensor([[0, 0], [0, 0]])))

log-probability given value with shape (2,):
 tensor(-2.4913) 

log-probability given value with shape (2,1):
 tensor([-2.4913, -2.4913])


In [14]:
from torch.distributions import Independent
normal_batch = Independent(normal_batch, reinterpreted_batch_ndims=1)
print(normal_batch.batch_shape)
print(normal_batch.event_shape)


torch.Size([])
torch.Size([2])


In [15]:
mvn_batch = MultivariateNormal(
    loc=torch.Tensor([[0, 1],[1, 2],[2, 3]]),
    scale_tril=torch.cholesky(torch.Tensor([[1., .2], [.2, .5]])))
mvn_batch

MultivariateNormal(loc: torch.Size([3, 2]), scale_tril: torch.Size([3, 2, 2]))

In [16]:
print("random sample with sample_shape ():\n",
      mvn_batch.sample(), "\n")
print("random sample with sample_shape (3,):\n",
      mvn_batch.sample(sample_shape=(3,)), "\n")
print("random sample with sample_shape (2, 3):\n",
      mvn_batch.sample(sample_shape=(2, 3)))


random sample with sample_shape ():
 tensor([[-1.1759,  0.7234],
        [ 2.2967,  2.6732],
        [ 2.4495,  3.2737]]) 

random sample with sample_shape (3,):
 tensor([[[0.9133, 1.2102],
         [0.9494, 1.6224],
         [1.4728, 3.7220]],

        [[0.5411, 0.7077],
         [0.8437, 2.5496],
         [2.4281, 2.4536]],

        [[0.0987, 0.6569],
         [0.3479, 1.8064],
         [3.7747, 2.6648]]]) 

random sample with sample_shape (2, 3):
 tensor([[[[-0.0631,  0.3916],
          [ 1.4256,  2.4096],
          [ 0.1691,  1.6225]],

         [[-1.9803,  1.8888],
          [ 1.2507,  1.1156],
          [ 3.0533,  2.8131]],

         [[-0.8355,  0.5726],
          [ 1.8916,  1.9377],
          [ 2.2285,  3.7143]]],


        [[[ 0.0131, -0.0956],
          [ 1.0848,  2.0932],
          [ 2.1682,  2.4639]],

         [[-0.5357, -0.7628],
          [ 1.2012,  2.5486],
          [ 2.7595,  2.9068]],

         [[-0.3642, -0.0413],
          [ 0.7936,  1.7178],
          [ 0.8948,  2.

In [17]:
mu_true = torch.tensor([5.])
sigma_true = torch.tensor([2.])
normal_model_true = Normal(
    loc=mu_true,
    scale=sigma_true)
print("normal model:\n", normal_model_true, "\n")

normal model:
 Normal(loc: tensor([5.]), scale: tensor([2.])) 



In [18]:
sample_size = 1000
x = normal_model_true.sample(sample_shape=(sample_size,))
loss_value = -torch.mean(torch.sum(normal_model_true.log_prob(x), dim = 1))
print("negative likelihood value is", loss_value)


negative likelihood value is tensor(2.1362)


In [19]:
epochs = 200
lr = 1.0
mu = torch.tensor([0.], requires_grad=True)
sigma = torch.tensor([1.], requires_grad=True)
optimizer = torch.optim.Adam([mu, sigma], lr=.5)
for epoch in range(epochs):
    normal_model = Normal(loc=mu, scale=sigma)
    loss_value = -torch.mean(normal_model.log_prob(x))
    optimizer.zero_grad()
    loss_value.backward() # compute the gradient
    optimizer.step()

In [20]:
print("ML mean by gradient descent:", mu)
print("ML std by gradient descent:", sigma)

ML mean by gradient descent: tensor([5.1666], requires_grad=True)
ML std by gradient descent: tensor([2.0451], requires_grad=True)


In [21]:
print("ML mean by formula:", torch.mean(x))
print("ML std by formula:", torch.std(x, unbiased=False))

ML mean by formula: tensor(5.1667)
ML std by formula: tensor(2.0409)


In [22]:
mu_true = torch.tensor([-1., 0., 1.])
sigma_tril_true = torch.tensor([[3., 0., 0.], [2., 1., 0.], [.4, .5, .5]])
mvn_model_true = MultivariateNormal(
    loc=mu_true,
    scale_tril=sigma_tril_true)
print("true mean vector: \n", mvn_model_true.mean)
print("true covariance matrix: \n", mvn_model_true.covariance_matrix)

true mean vector: 
 tensor([-1.,  0.,  1.])
true covariance matrix: 
 tensor([[9.0000, 6.0000, 1.2000],
        [6.0000, 5.0000, 1.3000],
        [1.2000, 1.3000, 0.6600]])


In [23]:
sample_size = 1000
x = mvn_model_true.sample(sample_shape=(sample_size,))
loss_value = -torch.mean(mvn_model_true.log_prob(x))
print("negative likelihood value is", loss_value)


negative likelihood value is tensor(4.6904)


In [24]:
epochs = 500
lr = .1
mu = torch.tensor(
    [0., 0., 0.], requires_grad=True)
sigma_tril = torch.tensor(
    [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]],
    requires_grad=True)
optimizer = torch.optim.Adam([mu, sigma_tril], lr=lr)

for epoch in range(epochs):
    mvn_model = MultivariateNormal(
    loc=mu,
    scale_tril=sigma_tril)
    loss_value = -torch.mean(mvn_model.log_prob(x))
    optimizer.zero_grad()
    loss_value.backward() # compute the gradient
    optimizer.step()

In [25]:
print("ML mean by gradient descent: \n",
      mu)
print("ML covariance by gradient descent: \n",
      sigma_tril @ torch.transpose(sigma_tril, 0, 1))

ML mean by gradient descent: 
 tensor([-0.9021,  0.0480,  0.9758], requires_grad=True)
ML covariance by gradient descent: 
 tensor([[9.2005, 6.3344, 1.2912],
        [6.3344, 5.3537, 1.3816],
        [1.2912, 1.3816, 0.6837]], grad_fn=<MmBackward>)


In [26]:
sample_mean = torch.mean(x, dim = 0)
sample_moment2 = (torch.transpose(x, 0, 1) @ x) / sample_size
sample_cov = sample_moment2 - torch.ger(sample_mean, sample_mean)
print("ML mean by formula: \n",
      sample_mean)
print("ML covariance by formula: \n",
      sample_cov)

ML mean by formula: 
 tensor([-0.9021,  0.0480,  0.9758])
ML covariance by formula: 
 tensor([[9.2005, 6.3344, 1.2912],
        [6.3344, 5.3537, 1.3816],
        [1.2912, 1.3816, 0.6837]])
